-- Complete Supabase Setup for Prime UAE Services
-- Run this file FIRST in Supabase SQL Editor
-- This creates all tables and sets up everything

-- ============================================
-- 1. CREATE TICKETS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS public.tickets (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  phone text not null,
  service text,
  message text not null,
  status text default 'open' check (status in ('open', 'pending', 'closed')),
  source text default 'website',
  -- Enhanced fields
  priority text default 'normal' check (priority in ('low', 'normal', 'high', 'urgent')),
  assigned_to uuid references auth.users(id),
  follow_up_date timestamp with time zone,
  estimated_value decimal,
  notes text,
  lead_score integer default 0
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.tickets ENABLE ROW LEVEL SECURITY;

-- Create policy to allow anonymous inserts (from contact form)
DROP POLICY IF EXISTS "Enable insert for everyone" ON public.tickets;
CREATE POLICY "Enable insert for everyone"
ON public.tickets FOR INSERT
TO anon
WITH CHECK (true);

-- Create policy to allow read/update for authenticated users (admin)
DROP POLICY IF EXISTS "Enable all for authenticated users" ON public.tickets;
CREATE POLICY "Enable all for authenticated users"
ON public.tickets FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

-- ============================================
-- 2. CREATE ADMIN SETTINGS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS public.admin_settings (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users(id) on delete cascade,
  full_name text,
  email text,
  notifications jsonb default '{"email": true, "push": false, "tickets": true, "updates": true}'::jsonb,
  theme text default 'light' check (theme in ('light', 'dark', 'system')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id)
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.admin_settings ENABLE ROW LEVEL SECURITY;

-- Create policy to allow authenticated users to manage their own settings
DROP POLICY IF EXISTS "Users can manage their own settings" ON public.admin_settings;
CREATE POLICY "Users can manage their own settings"
ON public.admin_settings FOR ALL
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- ============================================
-- 3. CREATE INDEXES FOR PERFORMANCE
-- ============================================
CREATE INDEX IF NOT EXISTS idx_tickets_status ON public.tickets(status);
CREATE INDEX IF NOT EXISTS idx_tickets_created_at ON public.tickets(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_tickets_email ON public.tickets(email);
CREATE INDEX IF NOT EXISTS idx_tickets_priority ON public.tickets(priority);
CREATE INDEX IF NOT EXISTS idx_tickets_assigned_to ON public.tickets(assigned_to);
CREATE INDEX IF NOT EXISTS idx_tickets_service ON public.tickets(service);

-- ============================================
-- 4. CREATE TRIGGER FUNCTION FOR UPDATED_AT
-- ============================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = timezone('utc'::text, now());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to automatically update updated_at
DROP TRIGGER IF EXISTS update_admin_settings_updated_at ON public.admin_settings;
CREATE TRIGGER update_admin_settings_updated_at
  BEFORE UPDATE ON public.admin_settings
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- 5. ADD COMMENTS FOR DOCUMENTATION
-- ============================================
COMMENT ON TABLE public.tickets IS 'Contact form submissions and customer inquiries';
COMMENT ON COLUMN public.tickets.priority IS 'Priority level: low, normal, high, urgent';
COMMENT ON COLUMN public.tickets.assigned_to IS 'User ID of the admin assigned to this ticket';
COMMENT ON COLUMN public.tickets.follow_up_date IS 'Date and time for follow-up action';
COMMENT ON COLUMN public.tickets.estimated_value IS 'Estimated revenue/value of this inquiry';
COMMENT ON COLUMN public.tickets.notes IS 'Internal notes and comments about the ticket';
COMMENT ON COLUMN public.tickets.lead_score IS 'Lead quality score (0-100)';

COMMENT ON TABLE public.admin_settings IS 'Admin user preferences and settings';

-- ============================================
-- SUCCESS MESSAGE
-- ============================================
DO $$
BEGIN
  RAISE NOTICE '✅ Setup complete! Tables created successfully.';
  RAISE NOTICE '📊 Tables: tickets, admin_settings';
  RAISE NOTICE '🔐 RLS policies enabled';
  RAISE NOTICE '⚡ Indexes created for performance';
END $$;

