
-- Create tickets table
create table public.tickets (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  phone text not null,
  service text,
  message text not null,
  status text default 'open' check (status in ('open', 'pending', 'closed')),
  source text default 'website'
);

-- Enable Row Level Security (RLS)
alter table public.tickets enable row level security;

-- Create policy to allow anonymous inserts (from contact form)
create policy "Enable insert for everyone"
on public.tickets for insert
to anon
with check (true);

-- Create policy to allow read/update for authenticated users (admin)
-- You might want to restrict this to specific users in production
create policy "Enable all for authenticated users"
on public.tickets for all
to authenticated
using (true)
with check (true);

-- Optional: Allow anon to read for development if you don't have auth set up yet
-- create policy "Enable read for everyone" on public.tickets for select to anon using (true);
